name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
  workflow_dispatch:  # cho phép chạy thủ công nếu cần

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/biay23092025/hr-anphat.git
          git push gitlab --all
          git push gitlab --tags
